
  type TokenResponse {
    status: String!
    token: String
    message: String
  }
  type GenericResponse {
    status: String!
    message: String
  }
  input IDRequest {
    token: String!
    id: Int!
  }
  type CategoryResponse {
    id: Int!
    category_str: String!
  }
  type ImageResponse {
    url: String
  }
  type GameResponse {
    id: Int
    name: String
    summary: String
    company: String
    category: CategoryResponse
    cover_url: ImageResponse
    screenshots: [ImageResponse]
    similar_game_ids: [Int]
    status: String
    message: String
  }

  type Mutation {
    register(username: String!, password: String!, email: String!): TokenResponse!
    login(email: String!, password: String!): TokenResponse!
    logout(token: String!): GenericResponse!
    addToFavorites(id: Int!, token: String!): GenericResponse
  }
  type Query {
    verify(token: String!): GenericResponse
    search(token: String!, query: String!): [GameResponse]
    game(token: String!, id: Int!): GameResponse
    popular: [GameResponse]
    favorites(token: String!): [GameResponse]
  }