
  type TokenResponse {
    status: String!
    token: String
    message: String
  }
  type GenericResponse {
    status: String!
    message: String
  }
  input IDRequest {
    token: String!
    id: Int!
  }
  type CategoryResponse {
    id: Int!
    category_str: String!
  }
  type ImageResponse {
    image_id: Int
    game_id: Int
    width: Int
    height: Int
    url: String
  }
  type GameResponse {
    id: Int
    name: String
    category: CategoryResponse
    covers: ImageResponse
    screenshots: [ImageResponse]
    similar_game_ids: [Int]
    status: String
    message: String
  }
  type Mutation {
    register(username: String!, password: String!, email: String!): GenericResponse!
    login(email: String!, password: String!): TokenResponse!
    logout(token: String!): GenericResponse!
  }
  type Query {
    verify(token: String!): GenericResponse
    search(token: String!, query: String!): [GameResponse]
    game(request: IDRequest!): GameResponse
  }